### ISSUE TITLE
Follow java coding standards

### ISSUE THREAD

**Issue by DePaul-KenYu** [lriver23/group2#1]
For example, package names should start with lower case.  Refer to standards in Lecture 1

**Comment by lriver23** [comment]
It looks like the package names that have this issue are: https://github.com/lriver23/group2/blob/9e0ac37f35d5f834a91db969cc049661fdde8cc6/src/main/java/edu/depaul/cdm/se452/group2/UserAuth/package-info.java#L1

https://github.com/lriver23/group2/blob/9e0ac37f35d5f834a91db969cc049661fdde8cc6/src/main/java/edu/depaul/cdm/se452/group2/OrderPlacement/package-info.java#L1

**Comment by MajidAbdul1** [comment]
Sorry professor.The issue is now resolved.
Thank you

**Comment by shoebsmk** [comment]
Hi professor, Thank you for pointing it out, We have changed it according to standers, Will take care next time.

**Comment by DePaul-KenYu** [comment]
Looks like OrderPlacement and UserAuth package is still upper case.

You may need to create the folder as lower case and copy the files there and delete the directory.  Be sure to update the package name to lower case as well after the copy.
